### ISSUE TITLE
`vendor` attr in `programs.fish`

### ISSUE THREAD

**Issue by heinwol** [jocelynthode/nixos-config#19]
Hi, @jocelynthode! Thank you for providing more integration with fish in nixos! I'm currently trying to make fish plugins work properly in my config, but I fail really hard for now)

You have [this line](https://github.com/jocelynthode/nixos-config/blob/52c423cc1c03f6aa8c6ea9a18897f2f6d6962888/modules/base/fish/default.nix#L91) in your config, but when I wrote the same nix shouted at me saying

> The option `home-manager.users.heinwol.programs.fish.vendor' does not exist

How did you make it work? I saw only one mention of `vendor` in your code
```
$ rg vendor
modules/base/fish/default.nix
91:    vendor = {
```

**Comment by jocelynthode** [comment]
Hey @heinwol nice to see that my config can help people out :)

If you look closely at this file you'll notice that I use both the fish module contained in nixpkgs and the one in home-manager. The vendor option is part of the `programs.fish` module that is is nixpkgs and not home-manager.

**Comment by heinwol** [comment]
Oh, really! I didn't notice that. Thanks for your help :) I believe it will bring me closer to a good-working terminal.

P.S. Now that I think about this. It feels like the need to configure both system and home-manager for some programs like fish isn't convenient. Why didn't the nix-community bring all of the options to home-manager... Well, I think I'm just too new to nix(os), so it's hard to grasp all those details. Anyway, I'm reeeeally pleased with nixos, it's the best distro ever!
